### ISSUE TITLE
Reference to the hadoop-etl-udfs repo

### ISSUE THREAD

**Issue by allipatev** [exasol/hive-virtual-schema#31]
Please note that User guide in this repo refers to the "create_kerberos_conn.py" file from the now archived repository hadoop-etl-udfs.

Now it just looks weird.

Maybe maintainer later even decides to remove the hadoop-etl-udfs repo, who knows ...

Please consider hosting the "create_kerberos_conn.py" file in an active project.

**Comment by ckunki** [comment]
File is available here https://github.com/exasol/virtual-schemas/blob/main/tools/create_kerberos_conn.py 
TODO: update User guide

**Comment by ckunki** [comment]
For file [udf_debug.py}(https://github.com/exasol/hadoop-etl-udfs/blob/main/tools/udf_debug.py) please see ticket https://github.com/exasol/virtual-schemas/issues/481.
